spring:
  application:
    name: pokefight
  main:
    banner-mode: off
  data:
    mongodb:
      uri: mongodb://localhost:27017/pokefight
      
server:
    port: 8585

pokefight:
    pokeApiUrlPrefix: https://pokeapi.co/api/v2/pokemon/